### ISSUE TITLE
Expose IMAP options.

### ISSUE THREAD

**Issue by witchbutter** [NTTCom-MS/eyp-dovecot#16]
Ordinarily it would be sufficient to add a file resource with a template to add options but in so doing I discovered that the main configuration file is controlled in config.pp like so:
```
  concat { '/etc/dovecot/dovecot.conf':
    ensure => 'present',
    owner  => 'root',
    group  => 'root',
    mode   => '0644',
  }

  concat::fragment{ '/etc/dovecot/dovecot.conf base':
    target  => '/etc/dovecot/dovecot.conf',
    order   => '00',
    content => template("${module_name}/dovecotconf.erb"),
  }

  concat::fragment{ '/etc/dovecot/dovecot.conf imap opts':
    target  => '/etc/dovecot/dovecot.conf',
    order   => '01',
    content => template("${module_name}/imap/imap_opts.erb"),
  }
```
Such that should I call out a file resource for `'/etc/dovecot/dovecot.conf'` it would never actually apply because concat overrides it.  Thus in order to allow additional options I had to add a stanza in a separate class like this:
```
  $dovecot_includes = "!include conf.d/*.conf
!include_try /usr/share/dovecot/protocols.d/*.protocol
!include_try local.conf
"

  concat::fragment{ '/etc/dovecot/dovecot.conf imap includes':
    target  => '/etc/dovecot/dovecot.conf',
    order   => '02',
    content => $dovecot_includes,
  }
```
There should be some facility in this forge module to append lines like this, I assume implemented in concat as well:
```
  class { 'dovecot':
    protocols       => [ 'imap' ],
    imap_options    => [
      '!include conf.d/*.conf',
      '!include_try /usr/share/dovecot/protocols.d/*.protocol',
      '!include_try local.conf',
    ],
  }
```

**Comment by jordiprats** [comment]
Hi,
I've introduced the ability to include config files using include_try on [0.1.15](https://github.com/NTTCom-MS/eyp-dovecot/releases/tag/0.1.15)

Hope this fixes your issue

kind regards,
